- on a scale from 1 to 5, how comfortable were you with this assignment?
- what was a win you had with this assignment?
- what was a challenge you had with this assignment?
- is there anything that you'd like some further information on?
- other stuff on your mind? work with anyone? tell us about it!
